# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111416)
$foreground = rgb(B9C7CA)
$color0 = rgb(393B3D)
$color1 = rgb(112328)
$color2 = rgb(172C31)
$color3 = rgb(1D353B)
$color4 = rgb(233F44)
$color5 = rgb(29484D)
$color6 = rgb(29484D)
$color7 = rgb(92A7AA)
$color8 = rgb(667577)
$color9 = rgb(172E36)
$color10 = rgb(1F3B42)
$color11 = rgb(26474E)
$color12 = rgb(2E545B)
$color13 = rgb(366067)
$color14 = rgb(366067)
$color15 = rgb(92A7AA)
