# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121212)
$foreground = rgb(CCCCCC)
$color0 = rgb(3A3A3A)
$color1 = rgb(242424)
$color2 = rgb(303030)
$color3 = rgb(3B3B3B)
$color4 = rgb(474747)
$color5 = rgb(525252)
$color6 = rgb(525252)
$color7 = rgb(AEAEAE)
$color8 = rgb(7A7A7A)
$color9 = rgb(313131)
$color10 = rgb(404040)
$color11 = rgb(4F4F4F)
$color12 = rgb(5F5F5F)
$color13 = rgb(6E6E6E)
$color14 = rgb(6E6E6E)
$color15 = rgb(AEAEAE)
